name: CI - Consulta CEP

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testes (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Lint (ruff)
        run: ruff --format=github .

      - name: Rodar testes
        run: pytest -q

  build-docker:
    name: Docker Build (verificação)
    runs-on: ubuntu-latest
    needs: test   # só roda se os testes passarem
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build imagem (somente build, sem push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: consulta-cep:ci
